### ISSUE TITLE
index.html 缓存好像有问题

### ISSUE THREAD

**Issue by zzswang** [zzswang/docker-nginx-react#10]
![image](https://user-images.githubusercontent.com/1524745/49775752-25da7280-fd34-11e8-9727-d831c2b2948e.png)

如图所示，index.html 已经有 ETag 了，但是貌似如果 index.html 文件有更新，线上还是需要强制刷新。

麻烦做如下测试：

1. example 里修改 index.html, 观察修改前后的 Etag 是否一样
2. 修改前后是否依然用了 缓存里 index.html

## 修复

1. 如果可以正常修复，就正常修复
2. 如果实在没办法，把 html 类型 从 Etag 里去掉，不再对 html 文件做缓存

**Comment by MiffyLiye** [comment]
在Chrome和Firefox上无法复现

**Comment by zzswang** [comment]
帮忙再看下这个

这个是 navinfo 的线上版本

http://navinfo-web.36node.com/

我这边出现直接打开的话，看到的还是老版本的网站。网站顶部导航 新老版本有区别。

这个好像不太好测试。难道和阿里云的负载均衡也有关系么

**Comment by zzswang** [comment]
不知道你之前访问过这个地址没有，如果没有的话，你先访问以下。等明天有新版发布，我通知一下你。看看有没有更新。

**Comment by MiffyLiye** [comment]
OK，本地缓存了
