### ISSUE TITLE
Env variables are not substituted in the app

### ISSUE THREAD

**Issue by Shaddix** [zzswang/docker-nginx-react#13]
> For all environments start with APP_, it will dynamically subset while server starting. You can put those envrionments in html/js/css files, we will handle it gracefully.
> 
> The above two environments are used by nginx, but it may also be interested with development. So we put APP_ prefix on them, make sure you can use them in your code.

From the above I assume, I could use something like `${APP_PATH_PREFIX}` in my app.
But actually if I put my app in /app (as recommended), the variables are not replaced. That's because `start-nginx.sh` only search&replace files in /usr/share/nginx/html, while my app is in /app:

    for f in `find /usr/share/nginx/html -regex ".*\.\(js\|css\|html\|json\|map\)"`

**Comment by Shaddix** [comment]
I mean, replacing
>for f in `find /usr/share/nginx/html

with 

>for f in `find /app

should do the trick

**Comment by zzswang** [comment]
Yes you are right, thanks :)

It seems we forgot to change it after path is updated, we will handle it.

**Comment by zzswang** [comment]
Besides `app` err, I think we should add some test, to make sure:

1. config will work as expected.
2. run test in circleci
3. add yarn release script, then it will publish on `hub.docker.com`

**Comment by MiffyLiye** [comment]
This fix could be dangerous, because it would substitute $APP_VARIABLE where it may not be expected.

For example, with ENV APP="'Hello'", it will replace
```
console.log('$APP_HI', $APP_HI)
```
to
```
console.log(''Hi'', 'Hi')
```

I suggest limit the files to be substituted with another ENV variable in future versions.

@Shaddix 
Is this feature used to substitute a short clear file or large / uglified files?
Would it still meet your needs if we only substitute explicitly specified files in the future?

**Comment by Shaddix** [comment]
We are running minified/compressed code on nginx servers, so it's kinda hard to specify the filename.
the way we are using it is like:
`export const APP_VERSION = '$APP_VERSION';`
and then we only use the constant in code, so personally I'm not afraid of messing up our app, but other people might use it differently, I agree.

I just thought from the docs, that it previously worked by replacing the $APP_SOMETHING everywhere, so the risks were already considered previously.

**Comment by zzswang** [comment]
I've merged the pull request.

We have the feature, but it depends on the user how to use it. And be careful :)


I'll prefer:

1. Do not use it directly in code.

2. Most of time, plz substitute your env during building process. Webpack should have such feature.

3. When some env need changed during runtime. First make it in building process. Like:
`APP_VERSION="$APP_VERSION" yarn build` . Then，we can substitute in runtime.
