### ISSUE TITLE
增加显示的缓存设置

### ISSUE THREAD

**Issue by zzswang** [zzswang/docker-nginx-react#19]
## 验收

- [ ] 尽量参考一个最佳实践
- [ ] 静态文件可以被正确缓存
- [ ] 文件有修改，可以被正确更新

用 examples/todoMVC 测试

**Comment by zzswang** [comment]
用 example 测试一下，看看是不是生效

**Comment by MiffyLiye** [comment]
参考 https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control
文件名带hash的js/css等内容不会变的文件可以加缓存，index.html这类内容会变的文件不能用Cache-Control加缓存。

## Caching static assets
For the files in the application that will not change, you can usually add aggressive caching by sending the response header below. This includes static files that are served by the application such as images, CSS files and JavaScript files, for example. In addition, see also the Expires header.

```
Cache-Control: public, max-age=31536000
```

**Comment by MiffyLiye** [comment]
参考 https://www.digitalocean.com/community/tutorials/how-to-implement-browser-caching-with-nginx-s-header-module-on-ubuntu-16-04

```
# Default server configuration
#

# Expires map
map $sent_http_content_type $expires {
    default                    off;
    text/html                  epoch;
    text/css                   max;
    application/javascript     max;
    ~image/                    max;
}

server {
    listen 80 default_server;
    listen [::]:80 default_server;

# Expires header
    expires $expires;
. . .
```

We’re using several different settings in this map:

* The default value is set to off, which will not add any caching control headers. It’s a safe bet for content we have no particular requirements on how the cache should work.
* For text/html, we set the value to epoch. This is a special value which results explicitly in no caching, which forces the browser to always ask if the website itself is up to date.
* For text/css and application/javascript, which are stylesheets and Javascript files, we set the value to max. This means the browser will cache these files for as long as it can, reducing the amount of requests considerably given that there are typically many of these files.
* The last setting is for ~image/, which is a regular expression that will match all file types containing image/ in their MIME type name (like image/jpg and image/png). Like stylesheets, there are often a lot of images on websites that can be safely cached, so we set this to max as well.

**Comment by zzswang** [comment]
整体方案应该挺好的，可以试一下

图片存在原地替换的可能性
