### ISSUE TITLE
[feat] health check

### ISSUE THREAD

**Issue by zzswang** [zzswang/docker-nginx-react#21]
provide health check

while call

```
${base}/health
```

return 200 json

```
{"version":"0.9.3","status":"OK","load":0.9}
```

- version: package.json's version
- status: always return ok
- load: cpu load

**Comment by cc3630** [comment]
若使用nginx执行sh，需加载lua模块

**Comment by zzswang** [comment]
REACT_APP_VERSION 出不来，这个不能放在环境变量里。只能想办法从 package.json 里读取
