### ISSUE TITLE
[bug] 404 问题 和 环境变量替换

### ISSUE THREAD

**Issue by zzswang** [zzswang/docker-nginx-react#7]
docker-nginx-react 是一个 docker for nginx 工程，用来给 spa 的前端火力支持

## 404 问题

前端路由的时候 先触发了 404，然后再跳转到对应页面

比如访问 

http://www.23.com/monitor

会先出现 404，

然后跳转到 正确页面

## 环境变量替换

测试一下，看能否工作，感觉有问题。修复之

**Comment by MiffyLiye** [comment]
原因是if导致try_files失效

Ref: 
https://www.nginx.com/resources/wiki/start/topics/depth/ifisevil/
https://www.digitalocean.com/community/tutorials/understanding-the-nginx-configuration-file-structure-and-configuration-contexts

**Comment by MiffyLiye** [comment]
trigger synchronization
